### PR TITLE
Fixes for Python 3.9

### LINKED ISSUE #61: Not working with python 3.9
I tried the Tasks example code from the pypeln README but it fails:

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/sebastian/test/venv/lib/python3.9/site-packages/pypeln/__init__.py", line 4, in <module>
    from . import thread
  File "/Users/sebastian/test/venv/lib/python3.9/site-packages/pypeln/thread/__init__.py", line 34, in <module>
    from .api.concat import concat
  File "/Users/sebastian/test/venv/lib/python3.9/site-packages/pypeln/thread/api/concat.py", line 8, in <module>
    from .to_stage import to_stage
  File "/Users/sebastian/test/venv/lib/python3.9/site-packages/pypeln/thread/api/to_stage.py", line 5, in <module>
    from ..stage import Stage
  File "/Users/sebastian/test/venv/lib/python3.9/site-packages/pypeln/thread/stage.py", line 8, in <module>
    from .queue import IterableQueue, OutputQueues
  File "/Users/sebastian/test/venv/lib/python3.9/site-packages/pypeln/thread/queue.py", line 17, in <module>
    class PipelineException(tp.NamedTuple, BaseException):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/typing.py", line 1820, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
python-BaseException
```

If I'm correct this has to do with python/cpython#19363

### LINKED ISSUE #71: [Bug] TypeError: Multiple inheritance with NamedTuple is not supported
**Describe the bug**
Exception during import pypeln .
For testing this bug i am creating a new virtual environment and installing pypeln in it using the tool python-poetry.

**Minimal code to reproduce**
```
% poetry new test_pypeln
Created package test_pypeln in test_pypeln

% cd test_pypeln 

% poetry add pypeln
Creating virtualenv test-pypeln-vKtIMPjL-py3.9 in /home/lks/.cache/pypoetry/virtualenvs
Using version ^0.4.7 for pypeln

Updating dependencies
Resolving dependencies... (0.8s)

Writing lock file

Package operations: 12 installs, 0 updates, 0 removals

  • Installing pyparsing (2.4.7)
  • Installing attrs (20.3.0)
  • Installing more-itertools (8.7.0)
  • Installing packaging (20.9)
  • Installing pluggy (0.13.1)
  • Installing py (1.10.0)
  • Installing wcwidth (0.2.5)
  • Installing coverage (5.5)
  • Installing pytest (5.4.3)
  • Installing pytest-cov (2.11.1)
  • Installing stopit (1.1.2)
  • Installing pypeln (0.4.7)

% poetry run python
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypeln
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lks/.cache/pypoetry/virtualenvs/test-pypeln-vKtIMPjL-py3.9/lib/python3.9/site-packages/pypeln/__init__.py", line 4, in <module>
    from . import thread
  File "/home/lks/.cache/pypoetry/virtualenvs/test-pypeln-vKtIMPjL-py3.9/lib/python3.9/site-packages/pypeln/thread/__init__.py", line 34, in <module>
    from .api.concat import concat
  File "/home/lks/.cache/pypoetry/virtualenvs/test-pypeln-vKtIMPjL-py3.9/lib/python3.9/site-packages/pypeln/thread/api/concat.py", line 8, in <module>
    from .to_stage import to_stage
  File "/home/lks/.cache/pypoetry/virtualenvs/test-pypeln-vKtIMPjL-py3.9/lib/python3.9/site-packages/pypeln/thread/api/to_stage.py", line 5, in <module>
    from ..stage import Stage
  File "/home/lks/.cache/pypoetry/virtualenvs/test-pypeln-vKtIMPjL-py3.9/lib/python3.9/site-packages/pypeln/thread/stage.py", line 8, in <module>
    from .queue import IterableQueue, OutputQueues
  File "/home/lks/.cache/pypoetry/virtualenvs/test-pypeln-vKtIMPjL-py3.9/lib/python3.9/site-packages/pypeln/thread/queue.py", line 15, in <module>
    class PipelineException(tp.NamedTuple, BaseException):
  File "/usr/lib/python3.9/typing.py", line 1881, in _namedtuple_mro_entries
    raise TypeError("Multiple inheritance with NamedTuple is not supported")
TypeError: Multiple inheritance with NamedTuple is not supported
>>> 

```

**Expected behavior**
import successful, no output

**Library Info**
pypeln (0.4.7)

### PR DESCRIPTION
**Pull request by SimonBiggs**
* Fixes https://github.com/cgarciae/pypeln/issues/71
* Fixes https://github.com/cgarciae/pypeln/issues/61

### CODE REVIEW

**Comment by cgarciae** [comment]
Hey! Sorry for the delay. So far it looks good, however, black if failing.

**Comment by cgarciae** [comment]
Didn't mean to close it, wrong button.

**Comment by SimonBiggs** [comment]
> Sorry for the delay.

No need to be sorry :)

**Comment by cgarciae** [comment]
All good, thanks @SimonBiggs! 
Will do a release tonight with the updates.

**Comment by SimonBiggs** [comment]
> thanks @SimonBiggs!

My pleasure :)

> Will do a release tonight with the updates.

No need to rush on my behalf, I've been installing from my own git branch.

**Comment by cgarciae** [comment]
> I've been installing from my own git branch.

Nice! I assume its within another poetry project or did poetry figure out how to support `pip install git+...`?

**Comment by SimonBiggs** [comment]
Yeah a separate poetry project. I put the following in my toml file:

```toml
pypeln = { git = "https://github.com/RadiotherapyAI/pypeln", rev = "7727021b4775fb3ec26a84f8fc45547412d23720" }
```

**Pull request merged**
